extends: stylelint-config-standard-scss
plugins:
  - stylelint-order
rules:
  selector-class-pattern: null
  scss/at-extend-no-missing-placeholder: null
  scss/load-no-partial-leading-underscore: null
  rule-empty-line-before:
    - "always"
    - except: ["first-nested", "inside-block-and-after-rule"]
      ignore: ["after-comment"]
  order/properties-alphabetical-order: true
